version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

  spring_app:
    build: .
    container_name: spring_app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend: